import { spawnSync } from "node:child_process"
import { existsSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const nextEnv = join(root, "next-env.d.ts")

// next-env.d.ts is generated by Next and gitignored. CI and a fresh checkout
// still need the reference so `tsc --noEmit` can load Next's types.
if (!existsSync(nextEnv)) {
  writeFileSync(
    nextEnv,
    '/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n',
  )
}

const tsc = join(root, "node_modules", "typescript", "bin", "tsc")
// Server surface only. The Next UI still has older type errors (boards pages,
// audio, stickers, sidebar) that are outside this RLS hardening change.
const result = spawnSync(process.execPath, [tsc, "--noEmit", "-p", "tsconfig.ci.json"], {
  cwd: root,
  stdio: "inherit",
})
process.exit(result.status === null ? 1 : result.status)
